camera.o: camera.c ../include/cmds.h ../include/types.h \
 ../include/camera.h ../include/game_math.h ../include/logger.h \
 ../include/game.h ../include/entity.h ../include/obj.h \
 ../include/model.h ../include/sprite.h ../include/graphics3d.h
cmds.o: cmds.c ../include/cmds.h ../include/types.h ../include/logger.h
dict.o: dict.c ../include/dict.h ../include/dict_conversions.h \
 ../include/types.h
dict_conversions.o: dict_conversions.c ../include/dict_conversions.h \
 ../include/types.h ../include/game_math.h
enemy.o: enemy.c ../include/enemy.h ../include/entity.h \
 ../include/types.h ../include/obj.h ../include/model.h \
 ../include/sprite.h ../include/graphics3d.h ../include/unit.h \
 ../include/game_math.h
entity.o: entity.c ../include/entity.h ../include/types.h \
 ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/logger.h
game.o: game.c ../include/game.h ../include/types.h ../include/entity.h \
 ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/game_math.h ../include/parser.h \
 ../include/dict.h ../include/dict_conversions.h ../include/camera.h \
 ../include/logger.h ../include/grid.h ../include/player.h \
 ../include/enemy.h ../include/unit.h ../include/weapon.h
game_math.o: game_math.c ../include/game_math.h ../include/types.h \
 ../include/logger.h
graphics3d.o: graphics3d.c ../include/graphics3d.h ../include/logger.h \
 ../include/types.h ../include/shader.h ../include/game.h \
 ../include/entity.h ../include/obj.h ../include/model.h \
 ../include/sprite.h ../include/graphics3d.h
grid.o: grid.c ../include/grid.h ../include/types.h ../include/entity.h \
 ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/logger.h ../include/game_math.h
logger.o: logger.c ../include/logger.h ../include/types.h
main.o: main.c ../include/parser.h ../include/dict.h \
 ../include/dict_conversions.h ../include/types.h ../include/logger.h \
 ../include/graphics3d.h ../include/shader.h ../include/obj.h \
 ../include/model.h ../include/sprite.h ../include/graphics3d.h \
 ../include/sprite.h ../include/cmds.h ../include/entity.h \
 ../include/obj.h ../include/camera.h ../include/game.h \
 ../include/entity.h ../include/game_math.h ../include/grid.h
model.o: model.c ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/types.h ../include/logger.h
obj.o: obj.c ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/types.h ../include/logger.h
opengl_funcs.o: opengl_funcs.c ../include/opengl_funcs.h \
 ../include/types.h ../include/game.h ../include/entity.h \
 ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/logger.h
parser.o: parser.c ../include/parser.h ../include/dict.h \
 ../include/dict_conversions.h ../include/types.h
player.o: player.c ../include/player.h ../include/entity.h \
 ../include/types.h ../include/obj.h ../include/model.h \
 ../include/sprite.h ../include/graphics3d.h ../include/game.h \
 ../include/cmds.h ../include/unit.h ../include/logger.h \
 ../include/game_math.h ../include/weapon.h
shader.o: shader.c ../include/shader.h ../include/logger.h \
 ../include/types.h
sprite.o: sprite.c ../include/sprite.h ../include/graphics3d.h \
 ../include/types.h ../include/logger.h ../include/graphics3d.h \
 ../include/opengl_funcs.h ../include/game_math.h ../include/game.h \
 ../include/entity.h ../include/obj.h ../include/model.h \
 ../include/sprite.h
unit.o: unit.c ../include/unit.h ../include/entity.h ../include/types.h \
 ../include/obj.h ../include/model.h ../include/sprite.h \
 ../include/graphics3d.h ../include/grid.h ../include/game_math.h \
 ../include/logger.h ../include/game.h
weapon.o: weapon.c ../include/weapon.h ../include/types.h \
 ../include/entity.h ../include/obj.h ../include/model.h \
 ../include/sprite.h ../include/graphics3d.h ../include/cmds.h \
 ../include/unit.h ../include/player.h ../include/parser.h \
 ../include/dict.h ../include/dict_conversions.h ../include/logger.h \
 ../include/enemy.h ../include/game_math.h
